---
title: "TWCF Expt 1.3 Stats BU"
author: "Karen Tian"
output: github_document
---

## TWCF 1.1 Cue Gab Det Analysis  
• [alphaA](#alphaa)  

C1 p(saw grating | grating present) v A p(correct discrimination)  
• [AUC](#auc-of-c1va)  
• [alpha](#fitted-alpha-of-C1)

C2 p(saw orientation | grating present) v A p(correct discrimination)  
• [AUC](#auc-ofc2va)    
• [alpha](#fitted-alpha-of-C2)  


```{r setup, include=FALSE}
#### packages #### 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
knitr::opts_chunk$set(echo = TRUE)

#### set path #### 
wd  <- getwd()

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load C1 p(saw figure) data #### 
# analysisName_C1 = "main_expt_UCI+BU_C1_group";
analysisName_C1 = "main_expt_BU_C1_group";
dataName_C1 <- sprintf("%s/data/%s.csv",wd,analysisName_C1)
data_C1 <- read_csv(dataName_C1)

#### load C2 p(saw shape) data #### 
# analysisName_C2 = "main_expt_UCI+BU_C2_group";
analysisName_C2 = "main_expt_BU_C2_group";
dataName_C2 <- sprintf("%s/data/%s.csv",wd,analysisName_C2)
data_C2 <- read_csv(dataName_C2)

#### Change to categorical vars ####
data_C1$att <- as.factor(data_C1$att)
data_C1$subjectID <- as.factor(data_C1$subjectID)
data_C2$att <- as.factor(data_C2$att)
data_C2$subjectID <- as.factor(data_C2$subjectID)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("-1","1"), c("-1","0"), c("0","1") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))

# sites
site <- 1; # 2 
```

### alphaA
```{r alphaA, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data_C1
if (site ==1) {
print("1")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(alphaA),
  wid = .(subjectID),
  within = .(att),
  detailed = TRUE,
)
} else {
print("2")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(alphaA),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
}

knitr::kable(m_anova)

d <- data_C1 %>% group_by(att) %>% 
  summarize(
    mean = mean(alphaA),
    sd = sd(alphaA),
    sem = sd(alphaA)/sqrt(length(alphaA)))
knitr::kable(d)

p <- ggbarplot(data_C1, x="att", y="alphaA", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("fitted alpha of A") + guides(color="none", fill="none") + 
  stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.3,0.26,0.2)) + stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.38)

ggpar(p, ylim = c(0, 0.4))
```

### AUC of C1vA
```{r AUC_C1, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data_C1
if (site ==1) {
print("1")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(AUC),
  wid = .(subjectID),
  within = .(att),
  detailed = TRUE,
)
} else {
print("2")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(AUC),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
}
knitr::kable(m_anova)

d <- data_C1 %>% group_by(att) %>% 
  summarize(
    mean = mean(AUC),
    sd = sd(AUC),
    sem = sd(AUC)/sqrt(length(AUC)))
knitr::kable(d)

ggbarplot(data_C1, x="att", y="AUC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("AUC") + guides(color="none", fill="none") + 
stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.35, 0.3,0.25)) + 
stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.4)

# Cohen's d w small sample size correction (<50)
# small effect ~0.2
# medium effect ~0.5
# large effect ~0.8 
d_attI <- data_C1 %>% filter(att==-1)
d_attV <- data_C1 %>% filter(att==1)
cd = cohensD(
  d_attI$AUC,
  d_attV$AUC,
  method = "paired"
  )
sprintf("cohen's d = %f", cd)

# label="p.signif"
```

### fitted alpha of C1
```{r alphaC1, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data_C1
if (site ==1) {
print("1")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(alphaC),
  wid = .(subjectID),
  within = .(att),
  detailed = TRUE,
)
} else {
print("2")
  m_anova = ezANOVA(
  data = data_C1,
  dv = .(alphaC),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
}
knitr::kable(m_anova)

d <- data_C1 %>% group_by(att) %>% 
  summarize(
    mean = mean(alphaC),
    sd = sd(alphaC),
    sem = sd(alphaC)/sqrt(length(alphaC)))
knitr::kable(d)

p <- ggbarplot(data_C1, x="att", y="alphaC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("fitted alpha of C1(x)") + guides(color="none", fill="none") + 
  stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.3,0.26,0.2)) + stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.38)

ggpar(p, ylim = c(0, 0.4))
```

### AUC of C2vA
```{r AUC_C2, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data_C2
if (site ==1) {
print("1")
  m_anova = ezANOVA(
  data = data_C2,
  dv = .(AUC),
  wid = .(subjectID),
  within = .(att),
  detailed = TRUE,
)
} else {
print("2")
  m_anova = ezANOVA(
  data = data_C2,
  dv = .(AUC),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
}
knitr::kable(m_anova)

d <- data_C2 %>% group_by(att) %>% 
  summarize(
    mean = mean(AUC),
    sd = sd(AUC),
    sem = sd(AUC)/sqrt(length(AUC)))
knitr::kable(d)

ggbarplot(data_C2, x="att", y="AUC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("AUC") + guides(color="none", fill="none") + 
stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.35, 0.3,0.25)) + 
stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.4)

d_attI <- data_C2 %>% filter(att==-1)
d_attV <- data_C2 %>% filter(att==1)
cd = cohensD(
  d_attI$AUC,
  d_attV$AUC,
  method = "paired"
  )
sprintf("cohen's d = %f", cd)
```

### fitted alpha of C2
```{r alphaC2, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data_C2
if (site ==1) {
print("1")
  m_anova = ezANOVA(
  data = data_C2,
  dv = .(alphaC),
  wid = .(subjectID),
  within = .(att),
  detailed = TRUE,
)
} else {
print("2")
  m_anova = ezANOVA(
  data = data_C2,
  dv = .(alphaC),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
}
knitr::kable(m_anova)

d <- data_C2 %>% group_by(att) %>% 
  summarize(
    mean = mean(alphaC),
    sd = sd(alphaC),
    sem = sd(alphaC)/sqrt(length(alphaC)))
knitr::kable(d)

p <- ggbarplot(data_C2, x="att", y="alphaC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("fitted alpha of C2(x)") + guides(color="none", fill="none") + 
  stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.43,0.33,0.22)) + stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.6)

ggpar(p, ylim = c(0, 0.65))
```
