---
title: "TWCF FOHO BigANOVA2"
author: "Karen Tian"
date: "2024-02-21"
output: github_document
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
knitr::opts_chunk$set(echo = TRUE)

#### set path #### 
wd  <- getwd()

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load AUC data #### 
analysisName = "AUC_ANOVA2";
dataName <- sprintf("%s/%s.csv",wd,analysisName)
data <- read_csv(dataName)

#### Change to categorical vars ####
data$expt <- as.factor(data$expt)
data$site <- as.factor(data$site)
data$subject <- as.factor(data$subject)
data$att <- as.factor(data$att)
data$AUCMeasure <- as.factor(data$AUCMeasure)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

## ANOVA
```{r anova, echo = TRUE}
m_anova = ezANOVA(
  data = data,
  dv = .(AUC),
  wid = .(subject),
  within = .(att,AUCMeasure),
  between = .(site,expt),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

