---
title: "TWCF FOHO BigANOVA1"
author: "Karen Tian"
date: "2024-02-21"
output: github_document
---

```{r setup, echo = FALSE, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
library(report)
library(rempsyc) # for t-tests in nice tables
knitr::opts_chunk$set(echo = TRUE)

#### set path #### 
wd  <- getwd()

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load AUC data #### 
analysisName = "AUC_ANOVA1";
dataName <- sprintf("%s/%s.csv",wd,analysisName)
data <- read_csv(dataName)

#### Change to categorical vars ####
data$stimulus <- as.factor(data$stimulus)
data$task <- as.factor(data$task)
data$site <- as.factor(data$site)
data$subject <- as.factor(data$subject)
data$att <- as.factor(data$att)
data$AUCMeasure <- as.factor(data$AUCMeasure)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

## AUC of orientation discrimination vs overall visibility report 
```{r anova, echo = TRUE}
m_anova = ezANOVA(
  data = data,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,stimulus,task),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

## Detection (Experiments 1 & 3)
```{r det, echo = TRUE}
d <- data %>% filter(task=="1")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,stimulus),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

## Discrimination (Experiments 2 & 4)
```{r dis, echo = TRUE}
d <- data %>% filter(task=="2")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,stimulus),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

## Texture-defined figure-ground ovals (Experiments 1 & 2)
```{r FG, echo = TRUE}
d <- data %>% filter(stimulus=="1")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,task),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

## Contrast-defined gratings (Experiments 3 & 4)
```{r grating, echo = TRUE}
d <- data %>% filter(stimulus=="2")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,task),
  detailed = TRUE,
  )
knitr::kable(m_anova)
```

## Experiment 1
```{r expt1, echo = TRUE, out.width="50%"}
d <- data %>% filter(stimulus=="1",task=="1",AUCMeasure=="1")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site),
  detailed = TRUE,
  )
knitr::kable(m_anova)

# Calculates mean, sd, se
dsum <- d %>% group_by(att) %>% 
  summarise( 
    n=n(),
    mean=mean(AUC),
    sd=sd(AUC)
  ) %>%
  mutate( se=sd/sqrt(n))

# Bar plots of AUC by att for overall vs feature visibility
ggplot(data=dsum, aes(x=att, y=mean, fill=att)) + scale_fill_manual(values=colors) +
  geom_bar(position="dodge", na.rm = TRUE, stat="identity") +
  labs(x="Attention", y = "AUC") + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0.2)
```

### Paired t-tests 
```{r expt1stats, echo = FALSE, out.width="90%"}
# V vs I 
dt <- d %>% filter(att=="1"|att=="3")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 1: invalid vs valid")
my_table

# I v N
dt <- d %>% filter(att=="1"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 1: invalid vs neutral")
my_table

# V v N
dt <- d %>% filter(att=="3"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 1: valid vs neutral")
my_table
```

## Experiment 2
```{r expt2, echo = TRUE}
d <- data %>% filter(stimulus=="1",task=="2")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site),
  detailed = TRUE,
  )
knitr::kable(m_anova)

# Calculates mean, sd, se
dsum <- d %>% group_by(att) %>% 
  summarise( 
    n=n(),
    mean=mean(AUC),
    sd=sd(AUC)
  ) %>%
  mutate( se=sd/sqrt(n))

# Bar plots of AUC by att for overall vs feature visibility
ggplot(data=dsum, aes(x=att, y=mean, fill=att)) + scale_fill_manual(values=colors) +
  geom_bar(position="dodge", na.rm = TRUE, stat="identity") +
  labs(x="Attention", y = "AUC") + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0.2)
```

### Paired t-tests 
```{r expt2stats, echo = FALSE, out.width="90%"}
# V vs I 
dt <- d %>% filter(att=="1"|att=="3")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 2: invalid vs valid")
my_table

# I v N
dt <- d %>% filter(att=="1"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 2: invalid vs neutral")
my_table

# V v N
dt <- d %>% filter(att=="3"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 2: valid vs neutral")
my_table
```

## Experiment 3
```{r expt3, echo = TRUE}
d <- data %>% filter(stimulus=="2",task=="1")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site),
  detailed = TRUE,
  )
knitr::kable(m_anova)

# Calculates mean, sd, se
dsum <- d %>% group_by(att) %>% 
  summarise( 
    n=n(),
    mean=mean(AUC),
    sd=sd(AUC)
  ) %>%
  mutate( se=sd/sqrt(n))

# Bar plots of AUC by att for overall vs feature visibility
ggplot(data=dsum, aes(x=att, y=mean, fill=att)) + scale_fill_manual(values=colors) +
  geom_bar(position="dodge", na.rm = TRUE, stat="identity") +
  labs(x="Attention", y = "AUC") + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0.2)
```

### Paired t-tests 
```{r expt3stats, echo = FALSE, out.width="90%"}
# V vs I 
dt <- d %>% filter(att=="1"|att=="3")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 3: invalid vs valid")
my_table

# I v N
dt <- d %>% filter(att=="1"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 3: invalid vs neutral")
my_table

# V v N
dt <- d %>% filter(att=="3"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 3: valid vs neutral")
my_table
```

## Experiment 4
```{r expt4, echo = TRUE}
d <- data %>% filter(stimulus=="2",task=="2")
m_anova = ezANOVA(
  data = d,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site),
  detailed = TRUE,
  )
knitr::kable(m_anova)

# Calculates mean, sd, se
dsum <- d %>% group_by(att) %>% 
  summarise( 
    n=n(),
    mean=mean(AUC),
    sd=sd(AUC)
  ) %>%
  mutate( se=sd/sqrt(n))

# Bar plots of AUC by att for overall vs feature visibility
ggplot(data=dsum, aes(x=att, y=mean, fill=att)) + scale_fill_manual(values=colors) +
  geom_bar(position="dodge", na.rm = TRUE, stat="identity") +
  labs(x="Attention", y = "AUC") + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=0.2)
```

### Paired t-tests 
```{r expt4stats, echo = FALSE, out.width="90%"}
# V vs I 
dt <- d %>% filter(att=="1"|att=="3")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 4: invalid vs valid")
my_table

# I v N
dt <- d %>% filter(att=="1"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 4: invalid vs neutral")
my_table

# V v N
dt <- d %>% filter(att=="3"|att=="2")
t.test(dt$AUC ~ dt$att, paired = TRUE) %>% report %>% 
  as.data.frame() -> stats.table
names(stats.table) <- c(
  "Parameter", "Group", "Difference", "t", "df", "p", "CI",
  "CI_lower", "CI_upper","Method","Alternative",
  "Cohens_d","d_CI_low","d_CI_high"
)
my_table <- nice_table(stats.table, report="t.test", title="Expt 4: valid vs neutral")
my_table
```