---
title: "Subjective inflation statistics"
author: "Karen Tian"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    toc_depth: 2
    number_sections: true
    keep_tex: yes
latex_engine: pdflatex
header-includes:
  \usepackage{helvet}
  \renewcommand\familydefault{\sfdefault}
  \usepackage{caption}
  \usepackage{booktabs}
include-before:
 '`\newpage{}`{=latex}'
---

```{r setup, echo = FALSE, include=FALSE, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(lsr)
library(report)
library(rempsyc) # for t-tests in nice tables
knitr::opts_chunk$set(echo = TRUE)

#### set path #### 
wd  <- getwd()

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load AUC data #### 
analysisName = "AUC_ANOVA3";
dataName <- sprintf("%s/%s.csv",wd,analysisName)
data <- read_csv(dataName)

#### Change to categorical vars ####
data$expt <- as.factor(data$expt)
data$site <- as.factor(data$site)
data$subject <- as.factor(data$subject)
data$att <- as.factor(data$att)
data$AUCMeasure <- as.factor(data$AUCMeasure)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("1","3"), c("1","2"), c("2","3") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

## ANOVA 3: AUC of orientation discrimination vs task-relevant feature visibility report 
```{r anova, echo=FALSE}
test.names <- c("$\\beta$", "$\\textit{p}$", "$df_{res}$")

m_anova = ezANOVA(
  data = data,
  dv = .(AUC),
  wid = .(subject),
  within = .(att),
  between = .(site,expt),
  detailed = TRUE,
  )

anova.names <- c("Effect","DFn","DFd","SSn","SSd","F","p","p<0.05","$\\eta^2_G$")
knitr::kable(m_anova, digits=3, booktabs=T, linesep = " ",
             caption = 'AUC of overall stimulus visibility',
             escape=FALSE) %>% 
             # col.names=anova.names) %>% 
  kableExtra::kable_styling(latex_options = c("hold_position")) 
```
The statistical tests used in this table were repeated measures ANOVAs.

