---
title: "TWCF Expt 1.2 Stats BU"
author: "Karen Tian"
output: github_document
---

## TWCF 1.2 Cue Tex Discrimination Analyses  
• [alphaA](#alphaa)  

C p(ref stronger) v A p(correct discrimination)  
• [AUC](#auc-of-cva)  
• [Relative AUC](#relative-auc-of-cva)  
• [alpha](#fitted-alpha-of-C1)


```{r setup, include=FALSE}
#### packages #### 
suppressPackageStartupMessages(library(tidyverse))
library(ez)
library(foreach)
library(kableExtra)
library(ggplot2)
library(dplyr)
library(ggpubr)
knitr::opts_chunk$set(echo = TRUE)

#### set path #### 
wd  <- getwd()

#### anova setup #### 
options(contrasts=c("contr.sum","contr.poly"))

#### load C data #### 
analysisName = "main_expt_UCI+BU_C_group";
dataName <- sprintf("%s/data/%s.csv",wd,analysisName)
data <- read_csv(dataName)

#### Change to categorical vars ####
data$att <- as.factor(data$att)
data$subjectID <- as.factor(data$subjectID)

### Plotting setup #### 
colors = c("#F8A299","#CCCCCC","#98E6A1")
attComparison <- list( c("-1","1"), c("-1","0"), c("0","1") )

significance <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf),
symbols = c("****", "***", "**", "*", "ns"))
```

### alphaA
```{r alphaA, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data
m_anova = ezANOVA(
  data = data,
  dv = .(alphaA),
  wid = .(subjectID),
  within = .(att),
  between = .(site),
  detailed = TRUE,
)
knitr::kable(m_anova)

d <- data %>% group_by(att) %>% 
  summarize(
    median = median(alphaA),
    sd = sd(alphaA),
    se = sd(alphaA)/sqrt(length(alphaA)))

p <- ggbarplot(data, x="att", y="alphaA", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("fitted alpha of A") + guides(color="none", fill="none") + 
  stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.3,0.26,0.2)) + stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.38)

ggpar(p) # ylim = c(0, 1)
```

### AUC of CvA
```{r AUC_C, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
m_anova = ezANOVA(
  data = data,
  dv = .(AUC),
  wid = .(subjectID),
  within = .(att),
  between = .(site)
)
knitr::kable(m_anova)

d <- data %>% group_by(att) %>% 
  summarize(
    mean = mean(AUC),
    sd = sd(AUC),
    se = sd(AUC)/sqrt(length(AUC)))

# ggplot(d, aes(x = att, y = mean, fill=att)) +
#   geom_col(position = position_dodge(0)) +
#   geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width= 0.2, position=position_dodge(.9)) +
#   scale_fill_manual(values=colors) +
# scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) +
# ylab("AUC") +
# stat_compare_means(comparisons=attComparison, label.y = c(0.5, 0.4,0.3)) +
# stat_compare_means(label.y =1)

ggbarplot(data, x="att", y="AUC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("AUC") + guides(color="none", fill="none") + 
stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.13, 0.10, 0.06)) + 
stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.18)

# label="p.signif"
```

### Relative AUC of CvA
```{r relAUC_C, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
m_anova = ezANOVA(
  data = data,
  dv = .(relAUC),
  wid = .(subjectID),
  within = .(att),
  between = .(site)
)
knitr::kable(m_anova)

d <- data %>% group_by(att) %>% 
  summarize(
    mean = mean(relAUC),
    sd = sd(relAUC),
    se = sd(relAUC)/sqrt(length(relAUC)))

ggbarplot(data, x="att", y="relAUC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("Relative AUC") + guides(color="none", fill="none") + 
stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.50, 0.41, 0.3)) + 
stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.60)

# label="p.signif"
```

### fitted alpha of C
```{r alphaC1, echo=FALSE, message=FALSE, warning=FALSE, fig.align="left", fig.width=4, fig.height=3.2}
d <- data
m_anova = ezANOVA(
  data = data,
  dv = .(alphaC),
  wid = .(subjectID),
  within = .(att)
)
knitr::kable(m_anova)

d <- data %>% group_by(att) %>% 
  summarize(
    mean = mean(alphaC),
    sd = sd(alphaC),
    se = sd(alphaC)/sqrt(length(alphaC)))

p <- ggbarplot(data, x="att", y="alphaC", add=c("mean_se"), size=0.7, color="att", fill="att", palette=colors) + 
scale_x_discrete(name = "Attention",labels=c("Invalid","Neutral","Valid")) + 
ylab("fitted alpha of C(x)") + guides(color="none", fill="none") + 
  stat_compare_means(paired=TRUE, comparisons=attComparison, label.y = c(0.3,0.26,0.2)) + stat_anova_test(method="one_way_repeated",wid="subjectID",label.y = 0.38)

ggpar(p) #  ylim = c(0, 0.4))
```


